### 
POST http://localhost:8000/api/users/ HTTP/1.1
Content-Type: application/json

{
	"email": "hanahww3@gmail.com",
	"password": "12345678"
}

### 
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"email": "hanahww3@gmail.com",
	"password": "12345678"
}

###
POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4MTY3MTg5LCJpYXQiOjE3NTgxNjUzODksImp0aSI6ImE1Zjk1NzMxMzQ1NDRkNGVhZGE4NDkzM2UyNjU4ZDMzIiwidXNlcl9pZCI6IjEifQ.-Kg_-D09XWaanwq99voL168Yp6Ur5xAdEaj2Z3GxQSo

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"    
}

###
POST http://localhost:8000/api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4MTY3MTg5LCJpYXQiOjE3NTgxNjUzODksImp0aSI6ImE1Zjk1NzMxMzQ1NDRkNGVhZGE4NDkzM2UyNjU4ZDMzIiwidXNlcl9pZCI6IjEifQ.-Kg_-D09XWaanwq99voL168Yp6Ur5xAdEaj2Z3GxQSo

{
	"status": "pending",
	"items": [
		{
				"product": 2,
				"quantity": 2
		},
		{
				"product": 3,
				"quantity": 1
		}
	]	
}

###
PATCH http://localhost:8000/api/orders/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4MTc0NTU4LCJpYXQiOjE3NTgxNzI3NTgsImp0aSI6ImNiZDcxYTU1OWMyOTRjNDA5ZmIxY2ZkNDIxYTM5MTMzIiwidXNlcl9pZCI6IjIifQ.vxiFQwWHNCYVv-7xn5ONoFAeBO-460xYfp3Dsx9s-eE

{
	"status": "pending"
}