# Generated by Django 4.2.24 on 2025-09-14 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['owner', 'due_date'], name='todos_todo_owner_i_d97881_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['goal_id', 'due_date'], name='todos_todo_goal_id_0ef105_idx'),
        ),
    ]
